Replaced all programs with the bug fixed version

diff --git a/subg09 b/subg09
--- a/subg09
+++ b/subg09
@@ -30,7 +30,8 @@ if ( $#argv == 0) then
   echo "   Warning: If %nproc is set to 1, G09 job will be submitted in serial queue."
   echo "            If %nproc is 2 through 40, G09 job will be submitted in cf40 queue instead.\n"
   echo "   PBS bash shell script of cf40 queue is freely adjustable for other purpose."
-  echo "   GP-GPU/CUDA is not now supported in Gaussian 09.\n"
+  echo "   GP-GPU/CUDA is not now supported in Gaussian 09."
+  echo ""
   exit 0
 else
   set INPUTFILE = "$1"
@@ -55,16 +56,42 @@ else
   set OUTPUTFILE = "$FULLPATH/$OUTPUTNAME".out
 endif 
 
-set NPROCS = `grep '%nproc' $INPUTFILE | cut -d= -f2`
+if ( `grep -ic '%gpucpu' $INPUTFILE` == 1 ) then
+  echo "Error: GPU accelerator is not supported in Gaussian 09, please use Gaussian 16 instead."
+  exit 1
+else
 
-if ( $NPROCS !~ ^[0-9]+$ ) then
-  echo "Error: Number of %nproc specified in input must be positive integer from 1 to 40."
+if ( `grep -ic '\-\-link1\-\-' $INPUTFILE` >= 1 ) then
+  @ NUMJOB = ( `grep -ic '\-\-link1\-\-' $INPUTFILE` + 1 )
+  echo ""
+  echo "Warning: $INPUTNAME.com contains $NUMJOB calculations."
+endif
+
+if ( `grep -ic '%nprocshared' $INPUTFILE` >= 1 ) then
+  set GREPPAT = "%nprocshared"
+else if ( `grep -ic '%nprocs' $INPUTFILE` >= 1 ) then
+  set GREPPAT = "%nprocs"
+else
+  echo ""
+  echo "Warning: Processors/cores is set to 1."
+  set NPROCS = 1
+  set JOBQUEUE = serial
+  set WALLTIME = "96:00:00"
+  goto set_node
+endif
+
+set NPROCS_LIST = ( `grep -i "$GREPPAT" $INPUTFILE | cut -d= -f2` )
+
+set NPROCS = "$NPROCS_LIST[1]"
+
+if ( `echo $NPROCS | grep -c '[a-z][A-Z]'` == 1 ) then
+  echo "Error: Number of $GREPPAT specified in input must be positive integer from 1 to 40."
   exit 1
 endif
 
 if ( $NPROCS >= 41 ) then
    echo ""
-   echo "Warning: Value of %nproc is over 40. So %nproc will be set to 40."
+   echo "Warning: Value of $GREPPAT is over 40. So $GREPPAT will be set to 40."
    set NPROCS = 40
 endif
 
@@ -76,6 +103,7 @@ else if ($NPROCS >= 2) then
   set WALLTIME = "96:00:00"
 endif
 
+set_node:
 set NODES = 1
 set THREADS = "$NPROCS"
 
@@ -159,18 +187,20 @@ else
 endif
 
 submit:
-set PBS_SCRIPT = "$FULLPATH/submit.QC.$INPUTNAME.sh"
+set PBS_SCRIPT = "$FULLPATH/submit.G09.$INPUTNAME.sh"
 
 cat <<EOF > $PBS_SCRIPT
 #!/bin/bash 
 
-#PBS -l select=$NODES\:ncpus=$NPROCS
+#PBS -l select=${NODES}:ncpus=${NPROCS}:ompthreads=${THREADS}
 #PBS -l walltime=$WALLTIME
 #PBS -q $JOBQUEUE
 #PBS -N $JOBNAME
 #PBS -P $PROJ_ID
 
-#### This PBS script was generated by subg09 program ####
+#############################################################
+#### This PBS Pro script was generated by subg09 program ####
+#############################################################
 
 module purge
 module load gaussian/g09
