Add files via upload

diff --git a/subg16 b/subg16
--- a/subg16
+++ b/subg16
@@ -41,6 +41,11 @@ if (! -e $G16_DIR) then
   exit 1
 endif
 
+if (! -e $G19_EXE) then
+  echo "Error: Unable to locate g16 executable, please check again."
+  exit 1
+endif
+
 set INPUTNAME = `basename $INPUTFILE .com`
 set REALNAME = "$INPUTNAME".com
 set REALPATH = `realpath $REALNAME`
@@ -80,7 +85,6 @@ else
   echo "Warning: Processors/cores is set to 1."
   set NPROCS = 1
   set JOBQUEUE = serial
-  set WALLTIME = "96:00:00"
   goto set_node
 endif
 
@@ -100,7 +104,6 @@ endif
 
 if ("null$NPROCS" == "null1") then
   set JOBQUEUE = serial
-  set WALLTIME = "96:00:00"
   goto set_node
 endif
 
@@ -108,8 +111,8 @@ check_queue:
 
 echo ""
 echo "Optimal job queues: "
-echo "  [1]  ctest (00:30:00)"
-echo "  [2]  cf40  (96:00:00)"
+echo "  [1]  ctest"
+echo "  [2]  cf40"
 echo ""
 
 echo -n "Enter job queue [2]: "
@@ -117,10 +120,8 @@ set INPQUEUE = "$<"
 
 if ( "null$INPQUEUE" == "null" || $INPQUEUE == 2 ) then
   set JOBQUEUE = cf40
-  set WALLTIME = "96:00:00"
 else if ( $INPQUEUE == 1 ) then
   set JOBQUEUE = ctest
-  set WALLTIME = "00:30:00"
 else
   echo "Error: Your choice is incorrect."
   goto check_queue
@@ -198,7 +199,6 @@ echo "    CPU cores  :  $NPROCS"
 echo "  OMP Threads  :  $THREADS"
 echo "     Job Name  :  $INPUTNAME"
 echo "    Job Queue  :  $JOBQUEUE"
-echo "    Wall-Time  :  $WALLTIME"
 echo "   Project ID  :  $PROJ_ID"
 echo ""
 
@@ -218,7 +218,6 @@ cat <<EOF > $PBS_SCRIPT
 #!/bin/bash 
 
 #PBS -l select=${NODES}:ncpus=${NPROCS}:ompthreads=${THREADS}
-#PBS -l walltime=$WALLTIME
 #PBS -q $JOBQUEUE
 #PBS -N $JOBNAME
 #PBS -P $PROJ_ID
@@ -229,6 +228,8 @@ cat <<EOF > $PBS_SCRIPT
 
 module purge
 
+cd \$PBS_O_WORKDIR
+
 export SCRATCH_DIR=/work1/$USER/SCRATCH/g16/g16.pbs\${PBS_JOBID/\.srvc1/}
 if [ ! -d \$SCRATCH_DIR ]; then mkdir -p \$SCRATCH_DIR; fi
 
@@ -238,8 +239,6 @@ export PATH="/pkg/gaussian/nbo6/bin:\$PATH"
 export GAUSS_SCRDIR="\$SCRATCH_DIR"
 export GAUSS_EXEDIR="\$g16root/"
 export GAUSS_EXECUT="\$g16root/g16"
-
-cd \$PBS_O_WORKDIR
 
 \$GAUSS_EXECUT < \
 $INPUTFILE > \
@@ -267,7 +266,7 @@ subg16 is used to submit shared-memory Gaussian 16 calculation on a single node.
 
 This version of subg16 does not support GP-GPU accelerator.
 
-subg16 can recognize the number of OMP threads from the value of %nprocs line in input file.
+subg16 determines the number of OMP threads by the value of %nprocs line in input file.
 Sensible value of %nprocs are: 1, 2, 4, 8, 12, 16, 24, 32, and 36.
 
 TAIWANIA Policy: Max value of %nprocs is 40.
diff --git a/submolpro b/submolpro
--- a/submolpro
+++ b/submolpro
@@ -6,7 +6,9 @@
 # https://github.com/rangsimanketkaew/QM-on-TAIWANIA/
 
 ##############################################################
-set MOLPRO     = /pkg/molpro/bin
+set MOLPRO_VER = "2015"
+set MOLPRO     = "/pkg/molpro/bin"
+set MOLPRO_EXE = "$MOLPRO/molpro"
 ##############################################################
 set PROJ_ID_FILE = "$HOME/.proj_id"
 ##############################################################
@@ -17,7 +19,7 @@ if ( "$1" == "-help" || "$1" == "--help" || "$1" == "-h" || "$1" == "help" ) got
 
 if ($#argv == 0) then
   echo ""
-  echo "   Molpro 2015 Interactive Job Submission on TAIWANIA, NCHC, Taiwan"
+  echo "   Molpro $MOLPRO_VER Interactive Job Submission on TAIWANIA, NCHC, Taiwan"
   echo "   ----------------------------------------------------------------"
   echo ""
   echo "   Usage: submolpro [PPN] input[.com] [output[.out]] [-help]"
@@ -28,8 +30,14 @@ if ($#argv == 0) then
   exit 0
 endif
 
+
 if (! -e $MOLPRO) then
-  echo 'Error: Unable to locate Molpro top directory, please set $MOLPRO environment variable'
+  echo 'Error: Unable to locate Molpro top directory, please check $MOLPRO environment variable'
+  exit 1
+endif
+
+if (! -e $MOLPRO_EXE) then
+  echo 'Error: Unable to locate "molpro" executable, please check $MOLPRO_EXE environment variable'
   exit 1
 endif
 
@@ -103,7 +111,6 @@ endif
 if ($PPN == 1) then
   set PPN = 1
   set JOBQUEUE = serial
-  set WALLTIME = "96:00:00"
   goto check_resource
 endif
 
@@ -120,10 +127,8 @@ endif
 
 if ("null$INPQUEUE" == "null" || $INPQUEUE == 2) then
   set JOBQUEUE = cf40
-  set WALLTIME = "96:00:00"
 else if ($INPQUEUE == 1) then
   set JOBQUEUE = ctest
-  set WALLTIME = "00:30:00"
 else
   echo "Error: Your choice is incorrect."
   goto check_queue
@@ -207,7 +212,6 @@ echo "MPI processes  :  $PPN"
 echo "  OMP Threads  :  $THREADS"
 echo "     Job Name  :  $JOBNAME"
 echo "    Job Queue  :  $JOBQUEUE"   
-echo "    Wall-Time  :  $WALLTIME"
 echo "   Project ID  :  $PROJ_ID"
 echo ""
 
@@ -227,7 +231,6 @@ cat <<EOF > $PBS_SCRIPT
 #!/bin/bash 
 
 #PBS -l select=${NODES}:ncpus=${CPUS}:mpiprocs=${PPN}:ompthreads=${THREADS}
-#PBS -l walltime=$WALLTIME
 #PBS -q $JOBQUEUE
 #PBS -N $JOBNAME
 #PBS -P $PROJ_ID
@@ -236,6 +239,7 @@ cat <<EOF > $PBS_SCRIPT
 #### This PBS Pro script was generated by submolpro program ####
 ################################################################
 
+module purge
 module load intel/2018_u1
 
 cd \$PBS_O_WORKDIR
@@ -243,9 +247,9 @@ cd \$PBS_O_WORKDIR
 export SCRATCH_DIR=/work1/$USER/SCRATCH/molpro/molpro.pbs\${PBS_JOBID/\.srvc1/}
 if [ ! -d \$SCRATCH_DIR ]; then mkdir -p \$SCRATCH_DIR; fi
 
-export MOLPRO_EXE=$MOLPRO/molpro
-export INPUT=$INPUTFILE
-export OUTPUT=$OUTPUTFILE
+export MOLPRO_EXE="$MOLPRO_EXE"
+export INPUT="$INPUTFILE"
+export OUTPUT="$OUTPUTFILE"
 
 \$MOLPRO_EXE -n $PPN -d \$SCRATCH_DIR \$INPUT -o \$OUTPUT
 
diff --git a/subnwmult b/subnwmult
--- a/subnwmult
+++ b/subnwmult
@@ -6,6 +6,13 @@
 # https://github.com/rangsimanketkaew/QM-on-TAIWANIA/
 
 ################################################################
+set NWCHEM_VER = "6.8.0"
+set NWCHEM_TOP = "/pkg/nwchem/Casper/i18gcc6/nwchem-6.8.1-fixmrcc"
+################################################################
+set NWCHEM_TARGET = "LINUX64"
+set NWCHEM_EXE = "$NWCHEM_TOP/bin/$NWCHEM_TARGET/nwchem"
+set NWCHEM_RESRC = "/pkg/nwchem/etc/default.nwchemrc"
+################################################################
 set PROJ_ID_FILE = "$HOME/.proj_id"
 ################################################################
 
@@ -14,8 +21,8 @@ if ("$1" == "-help" || "$1" == "--help" || "$1" == "-h" || "$1" == "help") goto 
 if ($#argv == 0) then
 
 echo ""
-echo "  Multiple NWChem Interactive Job Submission on TAIWANIA, NCHC, Taiwan"
-echo "  --------------------------------------------------------------------"
+echo "  Multiple NWChem $NWCHEM_VER Interactive Job Submission on TAIWANIA, NCHC, Taiwan"
+echo "  --------------------------------------------------------------------------"
 echo ""
 echo "  Usage: subnwmult inp_1.nw [inp_2.nw | inp_3.nw | ... | inp_10.nw] [-help]"
 echo ""
@@ -24,9 +31,10 @@ exit 0
 
 endif
 
-set NWCHEM_TOP = "/pkg/nwchem/Casper/i18gcc6/nwchem-6.8.1-fixmrcc"
-set NWCHEM_TARGET = LINUX64
-set NWCHEM_EXE = "$NWCHEM_TOP/bin/$NWCHEM_TARGET/nwchem"
+if (! -f $NWCHEM_EXE) then
+  echo 'Error: Unable to locate "nwchem" executable in $NWCHEM_TOP/bin/$NWCHEM_TARGET/ directory.'
+  exit 1
+endif
 
 set INPUTSUB = ( $argv[*] )
 set NUM = "$#INPUTSUB"
@@ -81,8 +89,6 @@ endif
   set JOBTHREAD = 1
   echo -n "| Enter job queue: "
   set JOBQUEUE = "$<"
-  echo -n "| Enter job wall-time (e.g. 00:30:00 for 30 minutes): "
-  set JOBTIME = "$<"
 
 set LISTID = ( `get_su_balance | awk -F, '{print $2}' | xargs` )
 
@@ -146,7 +152,6 @@ echo "| CPU cores        = $JOBCPU (per node)"
 echo "| MPI process      = $JOBMPI (per node)"
 echo "| OMP THREADS      = $JOBTHREAD (per MPI process)"
 echo "| Job Queue        = $JOBQUEUE"
-echo "| Wall-time        = $JOBTIME"
 echo "| Project ID       = $PROJ_ID"
 echo "|"
 
@@ -172,7 +177,6 @@ cat <<EOF > $PBS_SCRIPT
 #!/bin/bash
 
 #PBS -l select=${JOBNODE}:ncpus=${JOBCPU}:mpiprocs=${JOBMPI}:ompthreads=${JOBTHREAD}
-#PBS -l walltime=$JOBTIME
 #PBS -q $JOBQUEUE
 #PBS -N $JOBNAME
 #PBS -P $PROJ_ID
@@ -201,12 +205,19 @@ export MPI_ROOT=\$I_MPI_ROOT/intel64
 export MPICC=\$MPI_ROOT/bin/mpiicc
 export MPICXX=\$MPI_ROOT/bin/mpiicpc
 export MPIFC=\$MPI_ROOT/bin/mpiifort
-if [ ! -f ~/.nwchemrc ]; then ln -s /pkg/nwchem/etc/default.nwchemrc ~/.nwchemrc; fi
+
+export NWCHEM_EXE=$NWCHEM_EXE
+export NWCHEM_TARGET="LINUX64"
+export NWCHEM_RESRC="$NWCHEM_RESRC"
+
+if [ ! -f ~/.nwchemrc ]; then ln -s \$NWCHEM_RESRC ~/.nwchemrc; fi
 
 export MACHLIST=\$PBS_O_WORKDIR/nodelist.\${PBS_JOBID/\.srvc1/}
 
-mpiexec.hydra -PSM2 -n $TOTALMPI $NWCHEM_EXE \
-$JOBINPUT > $JOBOUTPUT
+mpiexec.hydra -PSM2 -n $TOTALMPI \
+\$NWCHEM_EXE \
+$JOBINPUT > \
+$JOBOUTPUT
 
 EOF
 
@@ -228,7 +239,7 @@ cat << EOF | less
 subnwmult
 =========
 
-Multiple NWChem 6.8.1 Job Submissions on TAIWANIA cluster, NCHC, Taiwan.
+Multiple NWChem $NWCHEM_VER Job Submissions on TAIWANIA cluster, NCHC, Taiwan.
 
  - Max number of input files is 10.
  - Interactive Job PBS Professional supported.
diff --git a/suborca b/suborca
--- a/suborca
+++ b/suborca
@@ -6,8 +6,9 @@
 # https://github.com/rangsimanketkaew/QM-on-TAIWANIA/
 
 ##############################################################
-set ORCA_TOP = "/pkg/orca/orca.4.0.1.2"
 set ORCA_VER = "4.0.1.2"
+set ORCA_TOP = "/pkg/orca/orca.4.0.1.2"
+set ORVA_EXE = "$ORCA_TOP/orca"
 ##############################################################
 set PROJ_ID_FILE = "$HOME/.proj_id"
 ##############################################################
@@ -19,7 +20,7 @@ if ( "$1" == "-help" || "$1" == "--help" || "$1" == "-h" || "$1" == "help" ) got
 if ($#argv == 0) then
 
 echo ""
-echo "   ORCA 4.0.1.2 Interactive Job Submission on TAIWANIA, NCHC, Taiwan"
+echo "   ORCA $ORCA_VER Interactive Job Submission on TAIWANIA, NCHC, Taiwan"
 echo "   -----------------------------------------------------------------"
 echo ""
 echo "   Usage: suborca input[.inp] [output[.out]] [-help]"
@@ -38,6 +39,11 @@ endif
 
 if (! -e $ORCA_TOP) then
   echo 'Error: Unable to locate ORCA top directory, please set $ORCA_TOP environment variable'
+  exit 1
+endif
+
+if (! -e $ORCA_EXE) then
+  echo 'Error: Unable to locate "orca" executable, please check $ORCA_EXE environment variable'
   exit 1
 endif
 
@@ -74,7 +80,6 @@ set NUMPAL = `grep '^!' $INPUTFILE | egrep -wio 'pal[1-9]+' | wc -l`
 if ( $NUMPAL == 0 ) then
   set CPUS = 1
   set JOBQUEUE = serial
-  set WALLTIME = "96:00:00"
   goto jobname
 else if ( $NUMPAL == 1 ) then
   set CPUS = `grep '^!' $INPUTFILE | egrep -wio 'pal[1-9]+' | sed -e 's/pal//I'`
@@ -90,16 +95,13 @@ endif
 if ( $CPUS == 1 ) then
   set CPUS = 1
   set JOBQUEUE = serial
-  set WALLTIME = "96:00:00"
 else if ( $CPUS >= 2 && $CPUS <= 40 ) then
   set JOBQUEUE = cf40
-  set WALLTIME = "96:00:00"
 else if ( $CPUS > 40 ) then
   echo ""
   echo "Warning: Number of MPI processes is over 40. Hence, it will be set to 40."
   set CPUS = 40
   set JOBQUEUE = cf40
-  set WALLTIME = "96:00:00"
 endif
 
 jobname:
@@ -169,6 +171,7 @@ jobinfo:
 echo ""
 echo "      ----- Job Info -----"
 echo ""
+echo "          ORCA  :  $ORCA_EXE"
 echo "    Input file  :  $INPUTFILE"
 echo "   Output file  :  $OUTPUTFILE"
 echo "  Compute node  :  $NODES"
@@ -177,7 +180,6 @@ echo " MPI processes  :  $MPIPROCS"
 echo "   OMP Threads  :  $THREADS"
 echo "      Job Name  :  $JOBNAME"
 echo "     Job Queue  :  $JOBQUEUE"
-echo "     Wall-Time  :  $WALLTIME"
 echo "    Project ID  :  $PROJ_ID"
 echo ""
 
@@ -197,7 +199,6 @@ cat <<EOF > $PBS_SCRIPT
 #!/bin/bash 
 
 #PBS -l select=${NODES}:ncpus=${CPUS}:mpiprocs=${MPIPROCS}
-#PBS -l walltime=$WALLTIME
 #PBS -q $JOBQUEUE
 #PBS -N $JOBNAME
 #PBS -P $PROJ_ID
@@ -211,16 +212,18 @@ module load gcc/6.3.0
 
 cd \$PBS_O_WORKDIR
 
-export ORCA_TOP=${ORCA_TOP}
-export LD_LIBRARY_PATH="/usr/lib64:\$ORCA_TOP/../lib:\$ORCA_TOP/../openmpi-3.1.0-gcc6/lib:\$ORCA_TOP:\$LD_LIBRARY_PATH"
-export ORCA_SCRATCH_DIR=/work1/$USER/SCRATCH/orca/pbs.\${PBS_JOBID/\.srvc1/}
+export ORCA_TOP="$ORCA_TOP"
+export ORCA_EXE="\$ORCA_TOP/orca"
 export PATH="\$ORCA_TOP/../openmpi-3.1.0-gcc6/bin:\$ORCA_TOP:\$PATH"
+export LD_LIBRARY_PATH="/usr/lib64:\$ORCA_TOP/../lib:\$ORCA_TOP/../openmpi-3.1.0-gcc6/lib:\$ORCA_TOP:\$LD_LIBRARY_PATH"
+
+export ORCA_SCRATCH_DIR=/work1/$USER/SCRATCH/orca/pbs.\${PBS_JOBID/\.srvc1/}
 if [ ! -d \$ORCA_SCRATCH_DIR ]; then mkdir -p \$ORCA_SCRATCH_DIR; fi
 
 cd \$ORCA_SCRATCH_DIR
-ln -s $INPUTFILE \$ORCA_SCRATCH_DIR/${USERINP}.inp
+ln -s $INPUTFILE \$ORCA_SCRATCH_DIR/${USER_INP}.inp
 
-$ORCA_TOP/orca \$ORCA_SCRATCH_DIR/${USERINP}.inp > $OUTPUTFILE
+$ORCA_EXE \$ORCA_SCRATCH_DIR/${USER_INP}.inp > $OUTPUTFILE
 
 EOF
 
@@ -246,10 +249,11 @@ cat << EOF | less
 suborca
 =======
 
-suborca detects number of MPI processes from value of 'PALn' keyword which specified in input file,
+suborca determines the number of MPI processes by value of 'PALn' keyword in inputfile,
 where n is a sensible positive integer, such as 2, 4, 8, 12, 24, 36, 40.
 
-For example, the following is requesting 4 MPI processes for geometry optimization calculation.
+For example, the following is calculation control command that is requesting of 4 MPI processes 
+for geometry optimization calculation.
 
   !B3LYP def2-SVP Opt PAL4
 
diff --git a/subqchem b/subqchem
--- a/subqchem
+++ b/subqchem
@@ -6,10 +6,12 @@
 # https://github.com/rangsimanketkaew/QM-on-TAIWANIA/
 
 ##############################################################
-set QC         = /pkg/qchem/qc42.mpich
-set QCAUX      = $QC/qcaux/
-set QCRSH      = ssh
-set QCPLATFORM = LINUX_Ix86_64
+set QC_VER     = "4.2.2"
+set QC         = "/pkg/qchem/qc42.mpich"
+set QC_EXE     = "$QC/bin/qchem"
+set QCAUX      = "$QC/qcaux/"
+set QCRSH      = "ssh"
+set QCPLATFORM = "LINUX_Ix86_64"
 ##############################################################
 set PROJ_ID_FILE = "$HOME/.proj_id"
 ##############################################################
@@ -23,7 +25,7 @@ if ( "$1" == "-help" || "$1" == "--help" || "$1" == "-h" || "$1" == "help" ) got
 # no command line argument
 if ($#argv == 0) then
   echo ""
-  echo "   Q-Chem 4.2.2 Interactive Job Submission on TAIWANIA, NCHC, Taiwan"
+  echo "   Q-Chem $QC_VER Interactive Job Submission on TAIWANIA, NCHC, Taiwan"
   echo "   -----------------------------------------------------------------"
   echo ""
   echo "   Usage: subqchem [thread] input[.in] [output[.out]] [-help]"
@@ -37,6 +39,11 @@ endif
 # check QC top directory
 if (! -e $QC) then
   echo 'Error: Unable to locate Q-Chem top directory, please set $QC environment variable'
+  exit 1
+endif
+
+if (! -f $QC_EXE) then
+  echo 'Error: Unable to locate "qchem" executable in $QC directory.'
   exit 1
 endif
 
@@ -128,7 +135,6 @@ endif
 if ($CPUS == 1) then
   set CPUS = 1
   set JOBQUEUE = serial
-  set WALLTIME = "96:00:00"
   goto check_resource
 endif
 
@@ -146,10 +152,8 @@ endif
 
 if ("null$INPQUEUE" == "null" || $INPQUEUE == 2) then
   set JOBQUEUE = cf40
-  set WALLTIME = "96:00:00"
 else if ($INPQUEUE == 1) then
   set JOBQUEUE = ctest
-  set WALLTIME = "00:30:00"
 else
   echo "Error: Your choice is incorrect."
   goto check_queue
@@ -231,7 +235,6 @@ echo "    CPU cores  :  $CPUS"
 echo "  OMP Threads  :  $THREADS"
 echo "     Job Name  :  $JOBNAME"
 echo "    Job Queue  :  $JOBQUEUE"   
-echo "    Wall-Time  :  $WALLTIME"
 echo "   Project ID  :  $PROJ_ID"
 echo ""
 
@@ -251,7 +254,6 @@ cat <<EOF > $PBS_SCRIPT
 #!/bin/bash 
 
 #PBS -l select=${NODES}:ncpus=${CPUS}:ompthreads=${THREADS}
-#PBS -l walltime=$WALLTIME
 #PBS -q $JOBQUEUE
 #PBS -N $JOBNAME
 #PBS -P $PROJ_ID
@@ -260,6 +262,7 @@ cat <<EOF > $PBS_SCRIPT
 #### This PBS Pro script was generated by subqchem program ####
 ###############################################################
 
+module purge
 module load intel/2018_u1
 
 cd \$PBS_O_WORKDIR
@@ -272,11 +275,13 @@ export QCAUX=$QCAUX
 export QCSCRATCH=\$SCRATCH_DIR
 export QCRSH=$QCRSH
 export QCPLATFORM=$QCPLATFORM
-export QCHEMRUN=\$QC/bin/qchem
+export QCHEMRUN=$QC_EXE
 export QCTHREADS=$THREADS
 export OMP_NUM_THREADS=$THREADS
 
-\$QCHEMRUN -nt $THREADS $INPUTFILE $OUTPUTFILE
+\$QCHEMRUN -nt $THREADS \
+$INPUTFILE \
+$OUTPUTFILE
 
 EOF
 
