Fixed Intel command env

diff --git a/subnwchem b/subnwchem
--- a/subnwchem
+++ b/subnwchem
@@ -30,6 +30,7 @@ every_thing_starts_from_here:
 
 onintr int
 
+set OUTPUT_ARG2  = 0
 set GPU          = 0
 set USEGPU       = 0
 set ARMCI        = 0
@@ -41,9 +42,9 @@ set CLEAN_CASPER = 0
 set CLEAN_MPIPR  = 0
 
 echo ""
-echo "     ###############################################################"
-echo "    ##   NWChem $NWCHEM_VER Interactive PBS Pro Submission on TAIWANIA   ##"
-echo "   ###############################################################"
+echo "     #################################################################"
+echo "    ###   NWChem $NWCHEM_VER Interactive PBS Pro Submission on TAIWANIA   ###"
+echo "   #################################################################"
 echo ""
 
 #############################################
@@ -52,7 +53,7 @@ echo ""
 
 set ARGV_ORDER = "$#argv"
 if ($ARGV_ORDER == 0) then
-  echo "   Usage: subnwchem input [ gpu | casper | mpipr ] [ help ]"
+  echo "   Usage: subnwchem input[.nw] [output[.out]] [gpu | casper | mpipr | help]"
   echo ""
   exit 0
 else if ("null$1" == "nullhelp" || "null$1" == "null-help" || "null$1" == "null-h") then
@@ -61,31 +62,38 @@ endif
 
 if ($ARGV_ORDER == 1) then
   set INPUT_ARG1 = "$1"
+  set OUTPUT_ARG2 = 0
+  goto nwchem_def
 endif
 
 if ($ARGV_ORDER >1) then
   set INPUT_ARG1 = "$1"
   @ i = 2
   while ($i <= $ARGV_ORDER)
-    set ARGV = $argv[$i]
-#
-    if ("null$ARGV" == "nullhelp") then
-      goto help
-    else if ("null$ARGV" == "nullgpu") then
-      set USEGPU = 1
-    else if ("null$ARGV" == "nullcasper") then
-      set ARMCI = 1
-      set CASPER = 1
-    else if ("null$ARGV" == "nullmpipr") then
-      set ARMCI = 1
-      set MPIPR = 1
-    else 
-      echo "Error: Invalid command $ARGV"
-      echo -n "####### Enter to start help page. #######" 
-      set HELP = "$<"
-      clear
-      goto help
-      exit 1
+# Set OUTPUT to 2nd arguement
+    if ("$i" == "2") then
+      set OUTPUT_ARG2 = "$argv[2]"
+# Check another arguments
+    else
+      set ARGV = $argv[$i]
+      if ("null$ARGV" == "nullhelp") then
+        goto help
+      else if ("null$ARGV" == "nullgpu") then
+        set USEGPU = 1
+      else if ("null$ARGV" == "nullcasper") then
+        set ARMCI = 1
+        set CASPER = 1
+      else if ("null$ARGV" == "nullmpipr") then
+        set ARMCI = 1
+        set MPIPR = 1
+      else
+        echo "Error: Invalid command $ARGV"
+        echo -n "####### Enter to start help page. #######" 
+        set HELP = "$<"
+        clear
+        goto help
+        exit 1
+      endif
     endif
     @ i ++
   end
@@ -229,6 +237,14 @@ endif
 # Define name of output file.
 #############################################
 
+if ($OUTPUT_ARG2 != 0) then
+  set OUTPUTFILE = "$OUTPUT_ARG2"
+  set OUTPUTNAME = `basename $OUTPUTFILE .out`
+  set OUTPUTFILE = "$OUTPUTNAME".out
+  set JOBOUTPUT = "$FULLPATH/$OUTPUTFILE"
+  goto ask_gpu
+endif
+
 set noglob
 set JOBOUTPUT  = `basename $JOBINPUT .nw`.out
 unset noglob
@@ -237,16 +253,16 @@ set DEFAULTOUTPUT = "$JOBOUTPUT"
 if (! -e $JOBOUTPUT) then
   set OUTPUTNAME = `basename $JOBINPUT .nw`.out
 else
-@ i = 1
-while (-e $JOBOUTPUT)
-  echo "@  $JOBOUTPUT  already exists."
-  set noglob
-  set JOBOUTPUT = `basename $JOBINPUT .nw`.$i.out
-  set OUTPUTNAME = `basename $JOBINPUT .nw`.$i.out
-  unset noglob
-  @ i ++
-end
-set DEFAULTOUTPUT = "$JOBOUTPUT"
+  @ i = 1
+  while (-e $JOBOUTPUT)
+    echo "@  $JOBOUTPUT  already exists."
+    set noglob
+    set JOBOUTPUT = `basename $JOBINPUT .nw`.$i.out
+    set OUTPUTNAME = `basename $JOBINPUT .nw`.$i.out
+    unset noglob
+    @ i ++
+  end
+  set DEFAULTOUTPUT = "$JOBOUTPUT"
 endif
 
 #
@@ -903,6 +919,7 @@ cat <<EOF > $JOB_SCRIPT
 #### This PBS Pro script was generated by subnwchem program ####
 ################################################################
 
+module purge
 module load intel/2018_u1 cuda/8.0.61 gcc/6.3.0
 
 cd \$PBS_O_WORKDIR
@@ -913,7 +930,11 @@ ulimit -s unlimited
 export SCRATCH_DIR=/work1/$USER/SCRATCH/nwchem/nwchem.pbs\${PBS_JOBID/\.srvc1/}
 if [ ! -d \$SCRATCH_DIR ]; then mkdir -p \$SCRATCH_DIR; fi
 
+export I_MPI_FABRICS=shm:tmi
 export I_MPI_PIN_DOMAIN=omp
+export I_MPI_HYDRA_BRANCH_COUNT=-1
+export I_MPI_HYDRA_PMI_CONNECT=alltoall
+
 export MPI_ROOT=\$I_MPI_ROOT/intel64
 export MPICC=\$MPI_ROOT/bin/mpiicc
 export MPICXX=\$MPI_ROOT/bin/mpiicpc
@@ -936,10 +957,17 @@ EOF
 
 if ("null$NWCHEM_RUNTIME" == "nullGPU") then
 cat <<EOF >> $JOB_SCRIPT
+
+########################
 \$CASCLEAN
-mpirun -PSM2 -n $TOTALMPI $NWCHEM_EXE \
+########################
+
+mpiexec.hydra -PSM2 -n $TOTALMPI $NWCHEM_EXE \
 $JOBINPUT > $JOBOUTPUT
+
+########################
 \$CASCLEAN
+########################
 
 EOF
 
@@ -953,7 +981,7 @@ export ARMCI_NETWORK=ARMCI
 \$CASCLEAN
 ########################
 
-mpirun -PSM2 -n $TOTALMPI -genv CSP_NG 1 -genv LD_PRELOAD \$NWCHEM_CASLIB/libcasper.so \
+mpiexec.hydra -PSM2 -n $TOTALMPI -genv CSP_NG 1 -genv LD_PRELOAD \$NWCHEM_CASLIB/libcasper.so \
 $NWCHEM_EXE \
 $JOBINPUT > \
 $JOBOUTPUT
@@ -974,7 +1002,7 @@ export ARMCI_NETWORK=MPI-PR
 \$MPIPRCLEAN
 ########################
 
-mpirun -PSM2 -n $TOTALMPI $NWCHEM_EXE \
+mpiexec.hydra -PSM2 -n $TOTALMPI $NWCHEM_EXE \
 $JOBINPUT > \
 $JOBOUTPUT
 
@@ -993,7 +1021,7 @@ cat <<EOF >> $JOB_SCRIPT
 \$CASCLEAN
 ########################
 
-mpirun -PSM2 -n $TOTALMPI $NWCHEM_EXE \
+mpiexec.hydra -PSM2 -n $TOTALMPI $NWCHEM_EXE \
 $JOBINPUT > \
 $JOBOUTPUT
 
@@ -1024,19 +1052,25 @@ cat << EOF | less
 
  NAME            subnwchem  -  Interactive PBS Professional Job Submission for NWChem $NWCHEM_VER
 
- SYNOPSIS        subnwchem input [ gpu | casper | mpipr ] [ help ]
+ SYNOPSIS        subnwchem input[.nw] [output[.out]] [gpu | casper | mpipr | help]
 
- EXAMPLE         subnwchem input               Submit job on CPU node.
+ EXAMPLE         subnwchem water                             Run water.nw and print output to water.out.
 
-                 subnwchem input mpipr         Submit job on CPU node using MPI-PR. Recommended for medium & large jobs.
+                 subnwchem water.nw                          Run water.nw and print output to water.out.
 
-                 subnwchem input casper        Submit job on CPU node using Casper. Use Casper when MPI-PR fails.
+                 subnwchem water water-HF                    Run water.nw and print output to water-HF.out.
 
-                 subnwchem input gpu           Submit job on GPU node using CUDA.
+                 subnwchem H2.nw mpipr                       Request MPI-PR. \
+                                                                              >  Recommended for medium & large jobs.
+                 subnwchem H2.nw casper                      Request Casper. /   (Use Casper instead when MPI-PR fails)
 
-                 subnwchem input gpu mpipr     [x] Not yet supported.
+                 subnwchem H2.nw gpu                         Request GPU for CUDA run. Job will be submitted on GPU node.
+                                                             Output file is H2.out.
 
-                 subnwchem input gpu casper    Submit job on GPU node using CUDA and Casper.
+                 subnwchem H2.nw gpu mpipr                   [x] Not yet supported.
+
+                 subnwchem H2.nw H2-CCSDT gpu casper         Run H2.nw with CUDA and Casper on GPU node and print output
+                                                             to H2-CCSDT.out
 
  DESCRIPTION     subnwchem is c-shell program script designed to interactively submit NWChem job using PBS Pro scheduler.
                  Note that command line optional argument is case sensitive. Lowercase is only supported.
@@ -1050,7 +1084,8 @@ cat << EOF | less
                  dedicated to help asynchronous progress for high efficient scalable MPI calculation.
                  For example, request of 40 processes on 20 compute node each, the total MPI processes is 800.
                  If either Casper or MPI-PR is requested, 20 MPI processes are used as ghost (a.k.a. dummy) processes.
-                 Hence the total actual MPI processes is 40*20 - 20 = 780.
+                 Hence the total actual MPI processes is 40*20 - 20 = 780. By the way, you can request N+1 MPI processors
+                 to compensate the Ghost processor rather N MPI processors.
 
                  NWChem $NWCHEM_VER also supports General-Purpose Graphical Processing Unit (GP-GPU) and the CUDA platform.
                  GP-GPU/CUDA supports only the tensor contraction engine (TCE) module for coupled-cluster (CC) calculation.
@@ -1058,7 +1093,8 @@ cat << EOF | less
                  
  COMMANDS
                  input                 -   NWChem input file with or without .nw extension.
-                 gpu                   -   Requests GPU accelerator for CUDA utilization.
+                 output                -   NWChem output file with or without .out extension.
+                 gpu                   -   Requests GPU accelerator for CUDA to speed up calculation.
                  casper                -   Requests Casper method (against MPI-PR).
                  mpipr                 -   Requests MPI-PR method (against Casper).
                  help                  -   Open this help.
