Update suborca

diff --git a/suborca b/suborca
--- a/suborca
+++ b/suborca
@@ -21,9 +21,12 @@ echo ""
 echo "   ORCA 4.0.1.2 Interactive PBS Job Submission on TAIWANIA, NCHC, Taiwan"
 echo "   ---------------------------------------------------------------------\n"
 echo "   Usage: suborca input [output]\n"
-echo "   where input is ORCA input with or without .inp extension.\n"
-echo "   suborca reconizes the number of MPI ranks from the value of 'PAL' e.g. PAL4"
-echo "   and supports the ORCA PBS job submission with only OpenMPI.\n"
+echo "                    |"
+echo "                    |--> ORCA input file with or without .inp extension.\n"
+echo "   suborca detects the number of MPI processes from the value of 'PAL'"
+echo "   in program control line, which starts with '!', in ORCA input file."
+echo "   For example, \! B3LYP def2-SVP Opt PAL4  is requesting 4 MPI processes"
+echo "   for geometry optimization calculation using B3LYP/def2-SVP method.\n"
 
 exit 0
 
@@ -47,58 +50,64 @@ if ("null$INPUTFILE" == "null") then
   exit 1
 endif
 
-set INPUTNAME = `basename $INPUTFILE .inp`
-set REALNAME = "$INPUTNAME".inp
-set REALPATH = `realpath $REALNAME`
+set USERINP = `basename $INPUTFILE .inp`
+set INPUTNAME = "$USERINP".inp
+set REALPATH = `realpath $INPUTNAME`
 set FULLPATH = `dirname $REALPATH`
-set INPUTFILE = "$FULLPATH/$INPUTNAME".inp
+set INPUTFILE = "$FULLPATH/$USERINP".inp
 if (! -f $INPUTFILE) then
   echo "Error: Unable to locate $INPUTFILE"
   exit 1
 endif
 
 if ("null$2" == "null") then
-  set OUTPUTFILE = "$FULLPATH/$INPUTNAME".out
+  set OUTPUTFILE = "$FULLPATH/$USERINP".out
 else
   set OUTPUTNAME = `basename $2 .out`
   set OUTPUTFILE = "$FULLPATH/$OUTPUTNAME".out
 endif
 
-set CPUS = `grep -io 'pal[1-9]*' $INPUTFILE | sed -e 's/pal//I'`
-
-if ( $CPUS !~ ^[0-9]+$ ) then
-  echo "Error: The number of OMP Threads must be positive integer. Max value is 40 threads."
+if ( `grep -c '^!' $INPUTFILE` == "" ) then
+  echo "Error: No keyword line in input file. The keyword line must start with ! flag."
   exit 1
 endif
 
-if ($CPUS > 40 ) then
-  echo "Warning: OMP Threads is over 40. So it was set to 40."
-  set CPUS = 40
-else if ($CPUS < 1 ) then
-  echo "Error: The number of OMP Threads must be positive integer. Max value is 40 threads."
-  exit 1
-endif
+# w = match whole word, i = ignore case, o = number of occurrence
+set NUMPAL = `grep '^!' $INPUTFILE | egrep -wio 'pal[1-9]+' | wc -l`
 
-if ("null$CPUS" == "null") then
-  set CPUS = 40
-  set JOBQUEUE = cf40
-  set WALLTIME = "96:00:00"
-else if ($CPUS == 1) then
+if ( $NUMPAL == 0 ) then
   set CPUS = 1
   set JOBQUEUE = serial
   set WALLTIME = "96:00:00"
-else if ($CPUS >= 2 && $CPUS <= 40) then
-  set JOBQUEUE = cf40
-  set WALLTIME = "96:00:00"
-else
-  echo "Error: Available job queues for ORCA are 'serial cf40'."
+  goto jobname
+else if ( $NUMPAL == 1 ) then
+  set CPUS = `grep '^!' $INPUTFILE | egrep -wio 'pal[1-9]+' | sed -e 's/pal//I'`
+  if ( "null$CPUS" == "null" ) then
+    echo "Error: Please assign value of MPI processes, e.g. PAL4 or PAL8."
+    exit 1
+  endif
+else if ( $NUMPAL > 1 ) then
+  echo "Error: There is more than one 'PALn' keyword in keyword line."
   exit 1
 endif
 
+if ( $CPUS == 1 ) then
+  set CPUS = 1
+  set JOBQUEUE = serial
+  set WALLTIME = "96:00:00"
+else if ( $CPUS >= 2 && $CPUS <= 40 ) then
+  set JOBQUEUE = cf40
+  set WALLTIME = "96:00:00"
+else if ( $CPUS > 40 ) then
+  echo "\nWarning: Number of MPI processes is over 40. Hence, it will be set to 40."
+  set CPUS = 40
+  set JOBQUEUE = cf40
+  set WALLTIME = "96:00:00"
+endif
+
+jobname:
 set THREADS = "$CPUS"
-
-set JOBNAME = "$INPUTNAME"
-
+set JOBNAME = "$USERINP"
 set PROJ_ID = `get_su_balance | awk -F, '{print $2'}`
 
 #####################################################
@@ -125,7 +134,7 @@ else
 endif
 
 submit:
-set PBS_SCRIPT = "$FULLPATH/submit.QC.$INPUTNAME.sh"
+set PBS_SCRIPT = "$FULLPATH/submit.ORCA.$USERINP.sh"
 
 cat <<EOF > $PBS_SCRIPT
 #!/bin/bash 
@@ -136,7 +145,9 @@ cat <<EOF > $PBS_SCRIPT
 #PBS -N $JOBNAME
 #PBS -P $PROJ_ID
 
-#### This PBS script was generated by suborca program ####
+##############################################################
+#### This PBS Pro script was generated by suborca program ####
+##############################################################
 
 module load gcc/6.3.0
 
@@ -144,17 +155,15 @@ cd \$PBS_O_WORKDIR
 
 export ORCA_TOP=${ORCA_TOP}
 export LD_LIBRARY_PATH="/usr/lib64:\$ORCA_TOP/../lib:\$ORCA_TOP/../openmpi-3.1.0-gcc6/lib:\$ORCA_TOP:\$LD_LIBRARY_PATH"
-export ORCA_SCRATCH_DIR=/work1/$USER/scratch/orca/pbs.\${PBS_JOBID/\.srvc1/}
+export ORCA_SCRATCH_DIR=/work1/$USER/SCRATCH/orca/pbs.\${PBS_JOBID/\.srvc1/}
 export PATH="\$ORCA_TOP/../openmpi-3.1.0-gcc6/bin:\$ORCA_TOP:\$PATH"
-if [ ! -d \$ORCA_SCRATCH_DIR ] then mkdir -p \$ORCA_SCRATCH_DIR; fi
+if [ ! -d \$ORCA_SCRATCH_DIR ]; then mkdir -p \$ORCA_SCRATCH_DIR; fi
 
 cd \$ORCA_SCRATCH_DIR
+ln -s $INPUTFILE \$ORCA_SCRATCH_DIR/${USERINP}.inp
 
-ln -s \$PBS_O_WORKDIR/$INPUTFILE \$ORCA_SCRATCH_DIR/$OUTPUTFILE
+$ORCA_TOP/orca \$ORCA_SCRATCH_DIR/${USERINP}.inp > $OUTPUTFILE
 
-$ORCA_TOP/orca $INPUTFILE > \$PBS_O_WORKDIR/$OUTPUTFILE
-
-echo " ------ Done ------ "
 
 EOF
 
