Big updated !

diff --git a/subqchem b/subqchem
--- a/subqchem
+++ b/subqchem
@@ -8,42 +8,36 @@
 # Updated 20180622  Rangsiman Ketkaew  rangsiman1993@gmail.com
 ##############################################################
 set QC         = /pkg/qchem/qc42.mpich
-set QCAUX      = $QC/qcaux
+set QCAUX      = $QC/qcaux/
 set QCRSH      = ssh
 set QCPLATFORM = LINUX_Ix86_64
 ##############################################################
 
-set NODES = 1
-set GPU = 0
+set NODES = 1 #OpenMP
+set GPU = 0 #current runtime does not support GPU.
 
 onintr inter
 
+# no command line argument
 if ($#argv == 0) then
-
-echo ""
-echo "   Q-Chem Interactive PBS Job Submission on TAIWANIA, NCHC, Taiwan"
-echo "   ---------------------------------------------------------------\n"
-echo "   Usage: subqchem thread input [output]\n"
-echo "   where thread is number of OpenMP threads"
-echo "         input is Q-Chem input with or without .in extension.\n"
-echo "   Parallelizability of Q-Chem that run in parallel with shared-memory (OpenMP)"
-echo "   is better than that of non-shared memory (MPI).\n"
-echo "   This script supports the Q-Chem PBS job submission with only OpenMP."
-echo "   If you want to use MPI instead, talk to TAIWANIA staff.\n"
-
-exit 0
-
-else if ($#argv == 1) then
-  echo "Error: Please enter number of OMP Threads."
-  exit 1
-
-else
-  set CPUS = "$1"
-  set INPUTFILE = "$2"
-
+  echo ""
+  echo "   Q-Chem Interactive PBS Job Submission on TAIWANIA, NCHC, Taiwan"
+  echo "   ---------------------------------------------------------------\n"
+  echo "   Usage: subqchem [thread] input [output]\n"
+  echo "                       |      |      |"
+  echo "   Number of thread <--|      |      |--> Output uses baseame of input file."
+  echo "    (Default is 1)            | "
+  echo "                              |--> Input file with or without .in extension.\n"
+  echo "   Example: subqchem 16 water-opt.in                      (16 cores)" 
+  echo "            subqchem water-opt.in water-opt-tight.out     (serial run)\n"
+  echo "   Parallelizability of Q-Chem that run in parallel with shared-memory (OpenMP)"
+  echo "   is better than that of non-shared memory (MPI).\n"
+  echo "   This script supports the Q-Chem PBS job submission with only OpenMP."
+  echo "   If you want to use MPI instead, talk to TAIWANIA staff.\n"
+  exit 0
 endif
 
-
+# check QC top directory
 if (! -e $QC) then
   echo 'Error: Unable to locate Q-Chem top directory, please set $QC environment variable'
   exit 1
@@ -54,40 +48,97 @@ if (! -e $QCAUX) then
   exit 1
 endif
 
-if ( $CPUS !~ ^[0-9]+$ ) then
-  echo "Error: the number of OMP Threads must be positive integer. Max value is 40 threads."
+# subqchem input
+if ($#argv == 1) then
+  set CPUS = 1
+  set INPUTFILE = "$1"
+  set OUTPUTFILE = 0
+  goto check_argv
+endif
+
+if ($#argv == 2) then
+# subqchem input output
+  if ( $1 !~ ^[0-9]+$ ) then
+    set CPUS = 1
+    set INPUTFILE = "$1"
+    set OUTPUTFILE = "$2"
+    goto check_argv
+# subqchem thread input
+  else if ( $1 =~ ^[0-9]+$ ) then
+    set CPUS = "$1"
+    set INPUTFILE = "$2"
+    set OUTPUTFILE = 0
+    goto check_argv
+  endif
+endif
+
+# subqchem thread input output
+if ($#argv == 3) then
+  if ( $1 !~ ^[0-9]+$ ) then
+    echo "Error: the number of OMP Threads must be positive integer. Max value is 40 threads."
+    exit 1
+  else
+    set CPUS = "$1"
+    set INPUTFILE = "$2"
+    set OUTPUTFILE = "$3"
+    goto check_argv
+  endif
+endif
+
+if ($#argv > 3) then
+  echo "Error: Unable to recognize $4 command. Please assign only [number of threads] input and [output]."
+  exit 1
+endif
+
+check_argv:
+#check cpu cores
+if ($CPUS !~ ^[0-9]+$ ) then
+  echo "Error: the number of OMP Threads must be positive integer."
   exit 1
 endif
 
 if ($CPUS > 40 ) then
-  echo "Warning: OMP Threads is over 40. So it was set to 40."
+  echo "\nWarning: Value of threads you assigned is over 40. Thus, threads will be set to 40 automatically."
   set CPUS = 40
 else if ($CPUS < 1 ) then
   echo "Error: the number of OMP Threads must be positive integer. Max value is 40 threads."
   exit 1
 endif
 
-if ("null$CPUS" == "null") then
-  set CPUS = 40
-  set JOBQUEUE = cf40
-  set WALLTIME = "96:00:00"
-else if ($CPUS == 1) then
+if ($CPUS == 1) then
   set CPUS = 1
   set JOBQUEUE = serial
   set WALLTIME = "96:00:00"
-else if ($CPUS >= 2 && $CPUS <= 40) then
+  goto check_input
+endif
+
+echo ""
+echo "Optimal queues:  ctest (30 mins) [1]"
+echo "                 cf40            [2]"
+echo ""
+
+check_queue:
+if ($CPUS >= 2 && $CPUS <= 40) then
+  echo -n "Enter job queue [2]: "
+  set INPQUEUE = "$<"
+endif
+
+if ("null$INPQUEUE" == "null") then
+  set JOBQUEUE = cf40
+  set WALLTIME = "96:00:00"
+else if ($INPQUEUE == 1) then
+  set JOBQUEUE = ctest
+  set WALLTIME = "00:30:00"
+else if ($INPQUEUE == 2) then
   set JOBQUEUE = cf40
   set WALLTIME = "96:00:00"
 else
-  echo "Error: Available job queues for Q-Chem are 'serial cf40'."
-  exit 1
+  echo "Error: Your choice is wrong. Please enter either 1 or 2."
+  goto check_queue
 endif
 
-if ("null$INPUTFILE" == "null") then
-  echo "Error: Please enter input file."
-  exit 1
-endif
-
+#check input
+check_input:
 set INPUTNAME = `basename $INPUTFILE .in`
 set REALNAME = "$INPUTNAME".in
 set REALPATH = `realpath $REALNAME`
@@ -98,10 +149,11 @@ if (! -f $INPUTFILE) then
   exit 1
 endif
 
-if ("null$3" == "null") then
+#check output
+if ("null$OUTPUTFILE" == "null0") then
   set OUTPUTFILE = "$FULLPATH/$INPUTNAME".out
 else
-  set OUTPUTNAME = `basename $3 .out`
+  set OUTPUTNAME = `basename $OUTPUTFILE .out`
   set OUTPUTFILE = "$FULLPATH/$OUTPUTNAME".out
 endif
 
@@ -116,6 +168,8 @@ set PROJ_ID = `get_su_balance | awk -F, '{print $2'}`
 #####################################################
 
 echo "\n     ----- Job Info -----\n"
+echo "   Q-Chem top  :  $QC"
+echo '   Executable  :  $QC/exe/qcprog.exe\n'
 echo "   Input file  :  $INPUTFILE"
 echo "  Output file  :  $OUTPUTFILE"
 echo " Compute node  :  $NODES"
@@ -175,5 +229,4 @@ exit 0
 inter: 
   echo "\nError: you pressed Ctrl+C ...Quit...\n"
   exit 1
-
 
